### ISSUE TITLE
Bug: ContentTypeGroupChatMemberAdded

### ISSUE THREAD

**Issue by humanagent** [xmtp/xmtp-react-playground#12]
### Describe the bug

I'm experiencing a consistent error in the Playground when attempting to utilize ContentTypeGroupChatMemberAdded

<img width="783" alt="CleanShot 2023-07-29 at 08 50 30@2x" src="https://github.com/xmtp/xmtp-react-playground/assets/1447073/c1a5f0ea-f121-44cf-8ae0-8da914500cbb">

### Steps to reproduce the bug

1. Git clone the playground
2. `npm install`
3. `npm run dev`

###  Environment Details:
Os X
node v18.16.1 (npm v9.5.1)

**Comment by nplasterer** [comment]
The V2 implementation of group chat has been removed from the playground in favor of a V3 implementation coming soon.
